name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch upstream
        run: |
          git remote add upstream https://git.suckless.org/dwm
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge --ff-only upstream/master
          git push origin master
